import React from 'react';
import {SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View} from 'react-native';
type Destination = 'profile'|'addresses'|'loyalty'|'referrals'|'offers'|'claims'|'notifications'|'support'|'terms';
type Props = {onOpen: (destination: Destination) => void; onLogout: () => void};
const entries: {label: string; detail: string; destination: Destination}[] = [
  {label: 'Profile', detail: 'Personal details and preferences', destination: 'profile'}, {label: 'Addresses', detail: 'Saved pickup and delivery locations', destination: 'addresses'},
  {label: 'Loyalty', detail: 'Points balance and history', destination: 'loyalty'}, {label: 'Referrals', detail: 'Your referral code and rewards', destination: 'referrals'},
  {label: 'Coupons & offers', detail: 'Available savings', destination: 'offers'}, {label: 'Claims & refunds', detail: 'Order help and status', destination: 'claims'},
  {label: 'Notifications', detail: 'Order updates and messages', destination: 'notifications'}, {label: 'Support', detail: 'Help and contact options', destination: 'support'},
  {label: 'Terms', detail: 'Terms and conditions', destination: 'terms'},
];
export default function AccountScreen({onOpen, onLogout}: Props) {return <SafeAreaView style={styles.page}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Account</Text><Text style={styles.subtitle}>Manage your details, benefits and support.</Text><View style={styles.list}>{entries.map(entry => <TouchableOpacity key={entry.label} style={styles.row} onPress={() => onOpen(entry.destination)}><View style={styles.flex}><Text style={styles.label}>{entry.label}</Text><Text style={styles.detail}>{entry.detail}</Text></View><Text style={styles.arrow}>›</Text></TouchableOpacity>)}</View><TouchableOpacity style={styles.logout} onPress={onLogout}><Text style={styles.logoutText}>Log out</Text></TouchableOpacity></ScrollView></SafeAreaView>;}
const styles = StyleSheet.create({page: {flex: 1, backgroundColor: '#FAF9F6'}, content: {padding: 20, paddingBottom: 30}, title: {fontSize: 30, fontWeight: '800'}, subtitle: {color: '#67635B', marginTop: 5, marginBottom: 20}, list: {borderRadius: 16, overflow: 'hidden', borderWidth: 1, borderColor: '#E1DDD5', backgroundColor: '#fff'}, row: {padding: 15, flexDirection: 'row', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#DDD8CF'}, flex: {flex: 1}, label: {fontSize: 16, fontWeight: '800'}, detail: {color: '#6D685F', marginTop: 3}, arrow: {fontSize: 26, color: '#555'}, logout: {marginTop: 20, padding: 15, borderRadius: 14, borderWidth: 1, borderColor: '#D7B4B0', alignItems: 'center'}, logoutText: {fontWeight: '800', color: '#982C23'}});
