import React, {useMemo, useState} from 'react';
import {ActivityIndicator, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, TouchableOpacity, View} from 'react-native';
import type {AddressItem} from '../types/address';
import type {ServiceCategory, ServiceItem} from '../types/service';

type Props = {
  customerName: string | null;
  servicesLoading: boolean; servicesError: string; services: ServiceItem[]; categories: ServiceCategory[];
  addresses: AddressItem[]; selectedAddressId: string | null; cartItemCount: number;
  getQuantity: (serviceId: string) => number; onSelectAddress: (addressId: string) => void;
  onManageAddresses: () => void; onOpenCart: () => void; onOpenNotifications: () => void;
  onRetryServices: () => void; onUpdateQuantity: (service: ServiceItem, change: number) => void;
};

export default function HomeScreen(props: Props) {
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
  const [addressMenuOpen, setAddressMenuOpen] = useState(false);
  const selectedAddress = props.addresses.find(address => address.id === props.selectedAddressId);
  const visibleServices = useMemo(
    () => selectedCategory ? props.services.filter(service => service.categoryName === selectedCategory) : [],
    [props.services, selectedCategory],
  );

  return <SafeAreaView style={styles.page}><StatusBar barStyle="dark-content" /><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View style={styles.topRow}>
      <TouchableOpacity accessibilityRole="button" accessibilityLabel="Choose delivery address" style={styles.addressButton} onPress={() => setAddressMenuOpen(value => !value)}><Text style={styles.eyebrow}>DELIVER TO</Text><Text numberOfLines={1} style={styles.addressText}>{selectedAddress?.label || selectedAddress?.address_line1 || 'Choose an address'} ▾</Text></TouchableOpacity>
      <TouchableOpacity accessibilityRole="button" accessibilityLabel="Notifications" style={styles.iconButton} onPress={props.onOpenNotifications}><Text>🔔</Text></TouchableOpacity>
      <TouchableOpacity accessibilityRole="button" accessibilityLabel={`Cart with ${props.cartItemCount} items`} style={styles.iconButton} onPress={props.onOpenCart}><Text>🛒 {props.cartItemCount || ''}</Text></TouchableOpacity>
    </View>
    {addressMenuOpen ? <View style={styles.menu}>{props.addresses.map(address => <TouchableOpacity key={address.id} style={styles.menuItem} onPress={() => {props.onSelectAddress(address.id); setAddressMenuOpen(false);}}><Text style={styles.menuTitle}>{address.label || 'Saved address'}</Text><Text numberOfLines={1} style={styles.muted}>{address.address_line1}</Text></TouchableOpacity>)}<TouchableOpacity style={styles.menuItem} onPress={props.onManageAddresses}><Text style={styles.link}>{props.addresses.length ? 'Manage addresses' : 'Add delivery address'} →</Text></TouchableOpacity></View> : null}
    <Text style={styles.welcome}>{props.customerName ? `Welcome ${props.customerName}` : 'Welcome'}</Text>
    <Text style={styles.title}>Laundry care, made simple</Text><Text style={styles.subtitle}>Choose a category to see available services.</Text>
    <Text style={styles.sectionTitle}>Service categories</Text>
    {props.servicesLoading ? <ActivityIndicator accessibilityLabel="Loading services" /> : null}
    {props.servicesError ? <View style={styles.errorCard}><Text style={styles.error}>{props.servicesError}</Text><TouchableOpacity onPress={props.onRetryServices}><Text style={styles.link}>Try again</Text></TouchableOpacity></View> : null}
    {!props.servicesLoading && !props.servicesError && !props.categories.length ? <Text style={styles.empty}>No services are available right now.</Text> : null}
    <View style={styles.categories}>{props.categories.map(category => <TouchableOpacity key={`${category.id ?? ''}-${category.name}`} accessibilityRole="button" accessibilityState={{selected: selectedCategory === category.name}} style={[styles.categoryCard, selectedCategory === category.name && styles.categoryCardSelected]} onPress={() => setSelectedCategory(category.name)}><Text style={styles.categoryName}>{category.name}</Text><Text style={styles.muted}>{category.count} service{category.count === 1 ? '' : 's'}</Text></TouchableOpacity>)}</View>
    {selectedCategory ? <View style={styles.serviceSection}><Text style={styles.sectionTitle}>{selectedCategory}</Text>{visibleServices.length ? visibleServices.map(service => {const quantity = props.getQuantity(service.id); return <View key={service.id} style={styles.serviceCard}><View style={styles.flex}><Text style={styles.serviceName}>{service.name}</Text>{service.description ? <Text style={styles.muted}>{service.description}</Text> : null}<Text style={styles.price}>{service.price == null ? 'Price after inspection' : `₹${service.price.toFixed(2)} / ${service.pricingUnit}`}</Text></View>{quantity ? <View style={styles.stepper}><TouchableOpacity accessibilityLabel={`Remove ${service.name}`} onPress={() => props.onUpdateQuantity(service, -1)}><Text style={styles.step}>−</Text></TouchableOpacity><Text style={styles.quantity}>{quantity}</Text><TouchableOpacity accessibilityLabel={`Add ${service.name}`} onPress={() => props.onUpdateQuantity(service, 1)}><Text style={styles.step}>＋</Text></TouchableOpacity></View> : <TouchableOpacity style={styles.addButton} accessibilityLabel={`Add ${service.name}`} onPress={() => props.onUpdateQuantity(service, 1)}><Text style={styles.addText}>Add</Text></TouchableOpacity>}</View>;}) : <Text style={styles.empty}>{props.servicesLoading ? 'Loading services…' : props.servicesError ? 'Retry loading services to continue.' : 'No services are available in this category.'}</Text>}</View> : props.categories.length > 0 && !props.servicesLoading ? <View style={styles.prompt}><Text style={styles.promptTitle}>Select a category</Text><Text style={styles.muted}>Service items will appear here after you choose one.</Text></View> : null}
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({page: {flex: 1, backgroundColor: '#FAF9F6'}, content: {padding: 18, paddingBottom: 30}, flex: {flex: 1}, topRow: {flexDirection: 'row', alignItems: 'center', gap: 9}, addressButton: {flex: 1, borderRadius: 14, backgroundColor: '#fff', padding: 12, borderWidth: 1, borderColor: '#E4E1DA'}, eyebrow: {fontSize: 10, letterSpacing: 1, color: '#67635B', fontWeight: '700'}, addressText: {fontWeight: '700', marginTop: 3}, iconButton: {minWidth: 42, minHeight: 42, alignItems: 'center', justifyContent: 'center', borderRadius: 13, backgroundColor: '#fff', borderWidth: 1, borderColor: '#E4E1DA'}, welcome: {fontSize: 17, fontWeight: '800', color: '#4F4B44', marginTop: 24}, title: {fontSize: 30, lineHeight: 36, fontWeight: '800', marginTop: 8, color: '#161513'}, subtitle: {fontSize: 15, color: '#67635B', marginTop: 6}, sectionTitle: {fontSize: 19, fontWeight: '800', marginTop: 23, marginBottom: 11}, categories: {flexDirection: 'row', flexWrap: 'wrap', gap: 10}, categoryCard: {width: '48%', minHeight: 72, justifyContent: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: '#E4E1DA', borderRadius: 18, paddingVertical: 11, paddingHorizontal: 14}, categoryCardSelected: {borderColor: '#111', borderWidth: 2, backgroundColor: '#F3F0E9'}, categoryName: {fontWeight: '800', marginBottom: 3}, menu: {borderRadius: 14, borderWidth: 1, borderColor: '#D9D5CD', backgroundColor: '#fff', marginTop: 6, overflow: 'hidden'}, menuItem: {padding: 13, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#E8E5DF'}, menuTitle: {fontWeight: '700'}, serviceSection: {marginTop: 3}, serviceCard: {flexDirection: 'row', alignItems: 'center', gap: 12, padding: 15, borderRadius: 16, backgroundColor: '#fff', borderWidth: 1, borderColor: '#E4E1DA', marginBottom: 10}, serviceName: {fontWeight: '800', fontSize: 16}, price: {marginTop: 7, fontWeight: '700'}, addButton: {backgroundColor: '#111', borderRadius: 11, paddingHorizontal: 17, paddingVertical: 10}, addText: {color: '#fff', fontWeight: '800'}, stepper: {flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: '#111', borderRadius: 11, paddingHorizontal: 8, paddingVertical: 6}, step: {fontSize: 20, fontWeight: '700'}, quantity: {minWidth: 16, textAlign: 'center', fontWeight: '800'}, prompt: {padding: 22, marginTop: 18, backgroundColor: '#EFECE5', borderRadius: 16, alignItems: 'center'}, promptTitle: {fontSize: 17, fontWeight: '800', marginBottom: 5}, muted: {color: '#6D685F'}, link: {fontWeight: '800', color: '#151515'}, empty: {color: '#6D685F', paddingVertical: 12}, errorCard: {padding: 15, backgroundColor: '#FFF2F0', borderRadius: 14, gap: 8}, error: {color: '#9A241E'}});
